### ISSUE TITLE
Embedded sqld appears to be out of date, can't query from latest TS client

### ISSUE THREAD

**Issue by CodingDoug** [chiselstrike/turso-cli#543]
libsql-client-ts version 0.3.0 can't query the sqld running with `turso dev`:

```
LibsqlError: SERVER_ERROR: Server returned HTTP status 404. It seems that the libsql server is outdated, please try updating the database.
    at mapHranaError (.../node_modules/@libsql/client/lib-cjs/hrana.js:317:16)
    at HttpClient.execute (.../node_modules/@libsql/client/lib-cjs/http.js:84:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'SERVER_ERROR',
  [cause]: HttpServerError: Server returned HTTP status 404. It seems that the libsql server is outdated, please try updating the database.
      at errorFromResponse (.../node_modules/@libsql/hrana-client/lib-cjs/http/stream.js:223:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    status: 404
  }
}
```

**Comment by palmithor** [comment]
I’m experiencing the same. Why did you close @CodingDoug ? Do you have a solution?

**Comment by CodingDoug** [comment]
This @palmithor this was for an old version of both the client library and sqld.  Please try to update both to the latest available and try again.  If you still see a problem, please report back your versions and the steps you take to reproduce.

**Comment by rafakwolf** [comment]
Hello, I am seeing the same error. I just installed the library, so it is supposed to be the latest version

❯ sqld --version
sqld sqld 0.23.0 (52d8b8f1 2024-02-26)

not sure how can I upgrade it

thank you for any help
